name: android_esim_installer
description: "A Flutter plugin (Android-only, Java) to install eSIM profiles programmatically using `EuiccManager`."
version: 1.0.2
homepage: https://github.com/ejazrahim420
repository: https://github.com/ejazrahim420/android_esim_installer
issue_tracker: https://github.com/ejazrahim420/android_esim_installer/issues
license: MIT

environment:
  # sdk: ^3.7.2
  # flutter: '>=3.3.0'
  sdk: ">=2.18.0 <4.0.0"
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0


flutter:

  plugin:
    platforms:
      android:
        package: com.codewithejaz.android_esim_installer
        pluginClass: AndroidEsimInstallerPlugin
